2016-08-22 17:57:44,482 : INFO : Machine : Mission Pinball Framework Core Engine v0.30.26
2016-08-22 17:57:44,483 : DEBUG : Machine : Command line arguments: {'no_load_cache': False, 'mpfconfigfile': '/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/mpfconfig.yaml', 'pause': False, 'bcp': True, 'consoleloglevel': 20, 'loglevel': 10, 'configfile': ['config'], 'create_config_cache': True, 'logfile': 'logs/2016-08-22-17-57-44-mpf-Jeremys-MacBook-Pro.local.log', 'force_platform': None}
2016-08-22 17:57:44,483 : DEBUG : Machine : MPF path: /Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf
2016-08-22 17:57:44,483 : INFO : Machine : Machine path: /Users/jackbot/pinball/taxi
2016-08-22 17:57:44,483 : DEBUG : Machine : Command line arguments: {'no_load_cache': False, 'mpfconfigfile': '/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/mpfconfig.yaml', 'pause': False, 'bcp': True, 'consoleloglevel': 20, 'loglevel': 10, 'configfile': ['config'], 'create_config_cache': True, 'logfile': 'logs/2016-08-22-17-57-44-mpf-Jeremys-MacBook-Pro.local.log', 'force_platform': None}
2016-08-22 17:57:44,483 : DEBUG : Machine : Python version: 3.5.0
2016-08-22 17:57:44,483 : DEBUG : Machine : Platform: darwin
2016-08-22 17:57:44,483 : DEBUG : Machine : Python executable location: /Applications/MPF.app/Contents/Resources/python
2016-08-22 17:57:44,483 : DEBUG : Machine : 32-bit Python? False
2016-08-22 17:57:44,483 : DEBUG : Machine : Machine path: /Users/jackbot/pinball/taxi
2016-08-22 17:57:44,667 : INFO : Machine : Loading config from original files
2016-08-22 17:57:44,667 : DEBUG : YAML File Interface : Loading file: /Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/mpfconfig.yaml
2016-08-22 17:57:44,709 : INFO : Machine : Machine config file #1: /Users/jackbot/pinball/taxi/config/config
2016-08-22 17:57:44,709 : DEBUG : YAML File Interface : Loading file: /Users/jackbot/pinball/taxi/config/config.yaml
2016-08-22 17:57:44,736 : DEBUG : YAML File Interface : YAML error found in file /Users/jackbot/pinball/taxi/config/config.yaml. Line 285, Position 29
2016-08-22 17:57:44,736 : ERROR : root : YAML error found in file /Users/jackbot/pinball/taxi/config/config.yaml. Line 285, Position 29
Traceback (most recent call last):
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/file_interfaces/yaml_interface.py", line 304, in load
    config = YamlInterface.process(f, round_trip)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/file_interfaces/yaml_interface.py", line 334, in process
    return Util.keys_to_lower(yaml.load(data_string, Loader=MpfLoader))
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/main.py", line 75, in load
    return loader.get_single_data()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/constructor.py", line 57, in get_single_data
    node = self.get_single_node()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/composer.py", line 46, in get_single_node
    document = self.compose_document()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/composer.py", line 66, in compose_document
    node = self.compose_node(None, None)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/composer.py", line 97, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/composer.py", line 156, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/composer.py", line 97, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/composer.py", line 156, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/composer.py", line 97, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/composer.py", line 156, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/composer.py", line 95, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/composer.py", line 126, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/composer.py", line 97, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/composer.py", line 149, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/parser_.py", line 118, in check_event
    self.current_event = self.state()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/parser_.py", line 490, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/scanner.py", line 130, in check_token
    self.fetch_more_tokens()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/scanner.py", line 237, in fetch_more_tokens
    return self.fetch_value()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/ruamel/yaml/scanner.py", line 596, in fetch_value
    self.get_mark())
ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
  in "/Users/jackbot/pinball/taxi/config/config.yaml", line 285, column 29

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/commands/game.py", line 130, in __init__
    MachineController(mpf_path, machine_path, vars(args)).run()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/machine.py", line 100, in __init__
    self._load_config()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/machine.py", line 286, in _load_config
    self._load_config_from_files()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/machine.py", line 305, in _load_config_from_files
    config_type='machine'))
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/config_processor.py", line 57, in load_config_file
    config = FileManager.load(filename, verify_version, halt_on_error)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/file_manager.py", line 155, in load
    round_trip)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/file_interfaces/yaml_interface.py", line 313, in load
    "Position {}".format(filename, mark.line + 1, mark.column + 1))
ValueError: YAML error found in file /Users/jackbot/pinball/taxi/config/config.yaml. Line 285, Position 29
